#!/bin/bash
set -euo pipefail
export BATOCERA_ARCH_PLASMA_ENABLE_INPUTMETHOD="${BATOCERA_ARCH_PLASMA_ENABLE_INPUTMETHOD:-1}"
export BATOCERA_ARCH_PLASMA_OUTPUT_SCALE="${BATOCERA_ARCH_PLASMA_OUTPUT_SCALE:-1}"
export BATOCERA_ARCH_PLASMA_TOUCH_CALIBRATION_MATRIX="${BATOCERA_ARCH_PLASMA_TOUCH_CALIBRATION_MATRIX:-auto}"
export BATOCERA_ARCH_PLASMA_POINTER_ACCEL="${BATOCERA_ARCH_PLASMA_POINTER_ACCEL:--0.5}"
exec /usr/bin/batocera-arch-plasma-lxc "$@"
