#!/bin/bash


# Enlarge toolkit UI on handhelds; keep native 1080p framebuffer.
command -v batocera-ui-scale >/dev/null 2>&1 && eval "$(batocera-ui-scale env)"
batocera-mouse show
yuzu
batocera-mouse hide
