#!/bin/bash


# Enlarge toolkit UI on handhelds; keep native 1080p framebuffer.
command -v batocera-ui-scale >/dev/null 2>&1 && eval "$(batocera-ui-scale env)"
if test -z "${DISPLAY}"
then
	export DISPLAY=$(getLocalXDisplay)
fi

PATH=$PATH:PATH=$PATH:/usr/wine/wine-tkg/bin

XDG_CONFIG_HOME=/userdata/system/configs XDG_CACHE_HOME=/userdata/system/cache /usr/bin/melonDS
