#!/bin/bash


# Enlarge toolkit UI on handhelds; keep native 1080p framebuffer.
command -v batocera-ui-scale >/dev/null 2>&1 && eval "$(batocera-ui-scale env)"
export DISPLAY=$(getLocalXDisplay)

XDG_CONFIG_HOME=/userdata/system/configs \
XDG_DATA_HOME=/userdata/saves \
XDG_CACHE_HOME=/userdata/system/cache \
batocera-config-gpu-wrapper /usr/bin/scummvm
