#!/bin/bash


# Enlarge toolkit UI on handhelds; keep native 1080p framebuffer.
command -v batocera-ui-scale >/dev/null 2>&1 && eval "$(batocera-ui-scale env)"
# when the program is called from a non X environment, handle the mouse
if test -z "${DISPLAY}"
then
    export DISPLAY=$(getLocalXDisplay)
fi

batocera-mouse show
trap 'batocera-mouse hide' EXIT

XDG_CONFIG_HOME="/userdata/system/configs" \
XDG_DATA_HOME="/userdata/saves/switch" \
XDG_CACHE_HOME="/userdata/system/cache" \
QT_QPA_PLATFORM="xcb" \
batocera-config-gpu-wrapper /usr/bin/eden -platform xcb
