#!/bin/bash


# Enlarge toolkit UI on handhelds; keep native 1080p framebuffer.
command -v batocera-ui-scale >/dev/null 2>&1 && eval "$(batocera-ui-scale env)"
# when the program is called from a non X environment, handle the mouse
# maybe an other choice is better

if test -z "${DISPLAY}"
then
    export DISPLAY=$(getLocalXDisplay)
fi

XDG_CONFIG_HOME=/userdata/system/configs \
XDG_DATA_HOME=/userdata/saves/3ds \
XDG_CACHE_HOME=/userdata/system/cache \
SDL_JOYSTICK_HIDAPI=0 \
batocera-config-gpu-wrapper /usr/bin/azahar
