FullKeyboard=yes
JoyButton-0=A
JoyButton-1=X
JoyButton-2=B
JoyButton-3=Y
JoyButton-4=Lock
JoyButton-5=HelpI
JoyButton-6=HelpII
JoyButton-7=StickClick
JoyButton-8=L
JoyButton-9=R
JoyButton-10=Home
JoyButton-11=Unlock,R
JoyAxis-0=-1,Left
JoyAxis-1=1,Right
JoyAxis-2=-2,Up
JoyAxis-3=2,Down
