default:
  options:
    gpu_performance_profile: auto
    opengl_driver: native

ports:
  options:
    opengl_driver: native

atomiswave:
  options:
    flycast_renderer: 4
    opengl_driver: zink

dreamcast:
  options:
    flycast_renderer: 4
    opengl_driver: zink

gamecube:
  options:
    gfxbackend: Vulkan
    opengl_driver: zink

naomi:
  options:
    flycast_renderer: 4
    opengl_driver: zink

naomi2:
  options:
    flycast_renderer: 4
    opengl_driver: zink

n64dd:
  options:
    opengl_driver: zink

psx:
  options:
    duckstation_gfxbackend: Vulkan
    opengl_driver: zink

triforce:
  options:
    gfxbackend: Vulkan
    opengl_driver: zink

xbox:
  options:
    opengl_driver: zink

odcommander:
  options:
    gpu_performance_profile: highperformance

scummvm:
  options:
    gpu_performance_profile: highperformance

android:
  options:
    gpu_performance_profile: highperformance

waydroid:
  options:
    gpu_performance_profile: highperformance

advision:
  emulator: mame
  core:     mame
flash:
  emulator: lightspark
  core:     lightspark
fmtowns:
  emulator: libretro
  core:     mame
lcdgames:
  emulator: mame
  core:     mame
n64:
  emulator: libretro
  core:     mupen64plus-next
  options:
    mupen64plus-rdpPlugin: parallel
    mupen64plus-rspPlugin: parallel
    opengl_driver: zink
nds:
  emulator: libretro
  core:     melonds
3ds:
  emulator: azahar
  core:     azahar
  options:
    gfxbackend: vulkan
    citra_graphics_api: Vulkan
    azahar_graphics_api: 2
steam:
  emulator: steam
  core:     gamepadui
  options:
    bezel: none
    gamescope: false
    steam_session_mode: gamepadui
    steam_gamepadui: true
    steam_user: auto
    steam_extra_args: ""
    steam_noshaders: false
    steam_unset_mesa_loader_driver_override: false
    steam_proton_log: false
psp:
  emulator: libretro
  core: ppsspp
  options:
    gfxbackend: 3 (VULKAN)
ps2:
  emulator: aethersx2
  core:     aethersx2
  options:
    aethersx2_renderer: 14
    gfxbackend: Vulkan
    opengl_driver: zink
ps3:
  options:
    rpcs3_gfxbackend: Vulkan
psvita:
  options:
    vita3k_gfxbackend: Vulkan
switch:
  options:
    eden_backend: 1
    ryujinx_api: Vulkan
    yuzu_backend: 1
wii:
  options:
    gfxbackend: Vulkan
wiiu:
  options:
    cemu_gfxbackend: 1
plugnplay:
  emulator: mame
  core:     mame
pdp1:
  emulator: mame
  core:     mame
pv1000:
  emulator: mame
  core:     mame
gamate:
  emulator: mame
  core:     mame
crvision:
  emulator: mame
  core:     mame
gamecom:
  emulator: mame
  core:     mame
fm7:
  emulator: mame
  core:     mame
gamepock:
  emulator: mame
  core:     mame
apfm1000:
  emulator: mame
  core:     mame
bbc:
  emulator: mame
  core:     mame
adam:
  emulator: mame
  core:     mame
gmaster:
  emulator: mame
  core:     mame
astrocde:
  emulator: mame
  core:     mame
ti99:
  emulator: mame
  core:     mame
tutor:
  emulator: mame
  core:     mame
coco:
  emulator: mame
  core:     mame
archimedes:
  emulator: mame
  core:     mame
socrates:
  emulator: mame
  core:     mame
supracan:
  emulator: mame
  core:     mame
vsmile:
  emulator: mame
  core:     mame
xegs:
  emulator: mame
  core:     mame
xbox360:
  emulator: xenia-edge
  core:     xenia-edge
  options:
    gpu: Vulkan
    xenia_api: Vulkan
atom:
  emulator: mame
  core:     mame
electron:
  emulator: mame
  core:     mame
camplynx:
  emulator: mame
  core:     mame
vgmplay:
  emulator: mame
  core:     mame
vc4000:
  emulator: mame
  core:     mame
gp32:
  emulator: mame
  core:     mame
laser310:
  emulator: mame
  core:     mame
quake3:
  emulator: vkquake3
  core:     vkquake3
macintosh:
  emulator: clk
  core:     clk
saturn:
  emulator: ymir
  core:     ymir
  options:
    decorations: none
    hud_support: none
    opengl_driver: zink
oricatmos:
  emulator: clk
  core:     clk
