default:
  options:
    hud_support: true
    gpu_performance_profile: highperformance
    opengl_driver: zink

odcommander:
  options:
    gpu_performance_profile: highperformance

scummvm:
  options:
    gpu_performance_profile: highperformance

android:
  options:
    gpu_performance_profile: highperformance

waydroid:
  options:
    gpu_performance_profile: highperformance

ports:
  options:
    gpu_performance_profile: highperformance
    
advision:
  emulator: mame
  core:     mame
flash:
  emulator: lightspark
  core:     lightspark
fmtowns:
  emulator: libretro
  core:     mame
lcdgames:
  emulator: mame
  core:     mame
n64:
  emulator: libretro
  core:     mupen64plus-next
nds:
  emulator: libretro
  core:     melonds
3ds:
  options:
    gfxbackend: vulkan
    citra_graphics_api: Vulkan
    azahar_graphics_api: 2
steam:
  emulator: steam
  core:     steamos
  options:
    bezel: none
    gamescope: true
    steam_session_mode: steamos
    steam_gamepadui: true
    steam_user: auto
    steam_extra_args: ""
    steam_noshaders: false
    steam_unset_mesa_loader_driver_override: false
    steam_proton_log: false
ps2:
  emulator: aethersx2
  core:     aethersx2
plugnplay:
  emulator: mame
  core:     mame
pdp1:
  emulator: mame
  core:     mame
pv1000:
  emulator: mame
  core:     mame
gamate:
  emulator: mame
  core:     mame
crvision:
  emulator: mame
  core:     mame
gamecom:
  emulator: mame
  core:     mame
fm7:
  emulator: mame
  core:     mame
gamepock:
  emulator: mame
  core:     mame
apfm1000:
  emulator: mame
  core:     mame
bbc:
  emulator: mame
  core:     mame
adam:
  emulator: mame
  core:     mame
gmaster:
  emulator: mame
  core:     mame
astrocde:
  emulator: mame
  core:     mame
ti99:
  emulator: mame
  core:     mame
tutor:
  emulator: mame
  core:     mame
coco:
  emulator: mame
  core:     mame
archimedes:
  emulator: mame
  core:     mame
socrates:
  emulator: mame
  core:     mame
supracan:
  emulator: mame
  core:     mame
vsmile:
  emulator: mame
  core:     mame
xegs:
  emulator: mame
  core:     mame
switch:
  options:
    hud_support: true
xbox360:
  emulator: xenia-canary
  core:     xenia-canary
  options:
    hud_support: true
    xenia_api: Vulkan
    gpu: Vulkan
atom:
  emulator: mame
  core:     mame
electron:
  emulator: mame
  core:     mame
camplynx:
  emulator: mame
  core:     mame
vgmplay:
  emulator: mame
  core:     mame
vc4000:
  emulator: mame
  core:     mame
gp32:
  emulator: mame
  core:     mame
laser310:
  emulator: mame
  core:     mame
quake3:
  emulator: vkquake3
  core:     vkquake3
saturn:
  emulator: ymir
  core:     ymir
  options:
    decorations: none
    hud_support: none
oricatmos:
  emulator: clk
  core:     clk
