################################################################################
#
# xenia-edge
#
################################################################################
XENIA_EDGE_VERSION = d2b24e8a98ea13c9e5bc524b1bb4d16efa136c0
XENIA_EDGE_SITE = https://github.com/has207/xenia-edge.git
XENIA_EDGE_SITE_METHOD = git
XENIA_EDGE_GIT_SUBMODULES = YES
XENIA_EDGE_LICENSE = BSD
XENIA_EDGE_LICENSE_FILE = LICENSE
XENIA_EDGE_EMULATOR_INFO = xenia-edge.emulator.yml
XENIA_EDGE_SUPPORTS_IN_SOURCE_BUILD = NO

XENIA_EDGE_DEPENDENCIES = host-ninja sdl2 vulkan-headers vulkan-loader lz4 alsa-lib python-toml \
    qt6base qt6declarative

XENIA_EDGE_HOST_TOOLS_BUILDDIR = $(@D)/buildroot-host-tools

XENIA_EDGE_CONF_OPTS += -DCMAKE_BUILD_TYPE=Release
XENIA_EDGE_CONF_OPTS += -DXENIA_BUILD_TESTS=OFF
XENIA_EDGE_CONF_OPTS += -DXENIA_BUILD_MISC=OFF
XENIA_EDGE_CONF_OPTS += -DXENIA_ENABLE_LTO=OFF
XENIA_EDGE_CONF_OPTS += -DXENIA_HOST_SHADER_CC=$(XENIA_EDGE_HOST_TOOLS_BUILDDIR)/host_tools/xenia-shader-cc
XENIA_EDGE_CONF_ENV += QT_DIR=$(STAGING_DIR)/usr

define XENIA_EDGE_GEN_VERSION_H
	mkdir -p $(@D)
	printf '// Autogenerated by batocera buildroot.\n\
#ifndef GENERATED_VERSION_H_\n\
#define GENERATED_VERSION_H_\n\
#define XE_BUILD_BRANCH "edge"\n\
#define XE_BUILD_COMMIT "$(XENIA_EDGE_VERSION)"\n\
#define XE_BUILD_COMMIT_SHORT "$(shell echo $(XENIA_EDGE_VERSION) | cut -c1-9)"\n\
#define XE_BUILD_DATE __DATE__\n\
#define XE_BUILD_PR_NUMBER 0\n\
#endif  // GENERATED_VERSION_H_\n' > $(@D)/version.h
endef

define XENIA_EDGE_BUILD_HOST_SHADER_CC
	rm -rf $(XENIA_EDGE_HOST_TOOLS_BUILDDIR)
	mkdir -p $(XENIA_EDGE_HOST_TOOLS_BUILDDIR)/tmp
	cd $(XENIA_EDGE_HOST_TOOLS_BUILDDIR) && \
	PATH="$(HOST_DIR)/bin:$(HOST_DIR)/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \
	PKG_CONFIG="$(HOST_DIR)/bin/pkg-config" \
	PKG_CONFIG_SYSROOT_DIR="/" \
	PKG_CONFIG_LIBDIR="$(HOST_DIR)/lib/pkgconfig:$(HOST_DIR)/share/pkgconfig" \
	PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 \
	PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 \
	TMPDIR="$(XENIA_EDGE_HOST_TOOLS_BUILDDIR)/tmp" \
	CFLAGS= CXXFLAGS= CPPFLAGS= LDFLAGS= \
	$(HOST_DIR)/bin/cmake $(@D) \
		-G"Ninja" \
		-DCMAKE_MAKE_PROGRAM="$(HOST_DIR)/bin/ninja" \
		-DCMAKE_BUILD_TYPE=Release \
		-DCMAKE_INSTALL_PREFIX="$(HOST_DIR)" \
		-DCMAKE_C_COMPILER="$(HOSTCC_NOCCACHE)" \
		-DCMAKE_CXX_COMPILER="$(HOSTCXX_NOCCACHE)" \
		-DXENIA_BUILD_HOST_TOOLS_ONLY=ON \
		-DXENIA_BUILD_TESTS=OFF \
		-DXENIA_BUILD_MISC=OFF \
		-DXENIA_ENABLE_LTO=OFF
	PATH="$(HOST_DIR)/bin:$(HOST_DIR)/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \
	TMPDIR="$(XENIA_EDGE_HOST_TOOLS_BUILDDIR)/tmp" \
	CFLAGS= CXXFLAGS= CPPFLAGS= LDFLAGS= \
	$(HOST_DIR)/bin/cmake --build $(XENIA_EDGE_HOST_TOOLS_BUILDDIR) \
		--target xenia-shader-cc -j$(PARALLEL_JOBS)
endef

XENIA_EDGE_PRE_CONFIGURE_HOOKS += XENIA_EDGE_GEN_VERSION_H XENIA_EDGE_BUILD_HOST_SHADER_CC

define XENIA_EDGE_INSTALL_TARGET_CMDS
	find $(@D) -maxdepth 6 -name "xenia_edge" -type f -perm /111 \
	    | head -1 \
	    | xargs -I{} $(INSTALL) -D -m 0755 {} $(TARGET_DIR)/usr/xenia_edge/xenia_edge
	mkdir -p $(TARGET_DIR)/usr/bin
	ln -sf /usr/xenia_edge/xenia_edge $(TARGET_DIR)/usr/bin/xenia-edge

	mkdir -p $(TARGET_DIR)/usr/xenia_edge/platforms
	-cp $(STAGING_DIR)/usr/plugins/platforms/libqxcb.so \
	    $(TARGET_DIR)/usr/xenia_edge/platforms/ 2>/dev/null || true

	mkdir -p $(TARGET_DIR)/usr/share/xenia-edge/patches
	mkdir -p $(@D)/temp-patches
	( cd $(@D)/temp-patches && $(GIT) init && \
	  $(GIT) remote add origin https://github.com/xenia-canary/game-patches.git && \
	  $(GIT) config core.sparsecheckout true && \
	  echo "patches/*.toml" >> .git/info/sparse-checkout && \
	  $(GIT) pull --depth=1 origin main && \
	  mv -f patches/*.toml \
	      $(TARGET_DIR)/usr/share/xenia-edge/patches \
	)
	rm -rf $(@D)/temp-patches
endef

$(eval $(cmake-package))
$(eval $(emulator-info-package))
