################################################################################
#
# vulkan-validationlayers
#
################################################################################

VULKAN_VALIDATIONLAYERS_VERSION = vulkan-sdk-1.4.328.1
VULKAN_VALIDATIONLAYERS_SITE = https://github.com/KhronosGroup/Vulkan-ValidationLayers.git
VULKAN_VALIDATIONLAYERS_SITE_METHOD = git
VULKAN_VALIDATIONLAYERS_DEPENDENCIES = \
	spirv-headers \
	spirv-tools \
	vulkan-headers \
	vulkan-utility-libraries
VULKAN_VALIDATIONLAYERS_INSTALL_STAGING = YES

VULKAN_VALIDATIONLAYERS_CONF_OPTS += -DCMAKE_BUILD_TYPE=Release

ifeq ($(BR2_PACKAGE_WAYLAND),y)
VULKAN_VALIDATIONLAYERS_DEPENDENCIES += wayland
VULKAN_VALIDATIONLAYERS_CONF_OPTS += -DBUILD_WSI_WAYLAND_SUPPORT=ON
else
VULKAN_VALIDATIONLAYERS_CONF_OPTS += -DBUILD_WSI_WAYLAND_SUPPORT=OFF
endif

ifeq ($(BR2_PACKAGE_LIBXCB),y)
VULKAN_VALIDATIONLAYERS_DEPENDENCIES += libxcb
VULKAN_VALIDATIONLAYERS_CONF_OPTS += -DBUILD_WSI_XCB_SUPPORT=ON
else
VULKAN_VALIDATIONLAYERS_CONF_OPTS += -DBUILD_WSI_XCB_SUPPORT=OFF
endif

ifeq ($(BR2_PACKAGE_XLIB_LIBX11)$(BR2_PACKAGE_XLIB_LIBXRANDR),yy)
VULKAN_VALIDATIONLAYERS_DEPENDENCIES += xlib_libX11 xlib_libXrandr
VULKAN_VALIDATIONLAYERS_CONF_OPTS += -DBUILD_WSI_XLIB_SUPPORT=ON
else
VULKAN_VALIDATIONLAYERS_CONF_OPTS += -DBUILD_WSI_XLIB_SUPPORT=OFF
endif

$(eval $(cmake-package))
