################################################################################
#
# xenia-canary
#
################################################################################

ifeq ($(BR2_x86_64),y)
# Version: Commits on May 25, 2026
XENIA_CANARY_SOURCE = xenia_canary_windows.zip
XENIA_CANARY_VERSION = 505697f
XENIA_CANARY_SITE = \
    https://github.com/xenia-canary/xenia-canary/releases/download/$(XENIA_CANARY_VERSION)
XENIA_CANARY_LICENSE = BSD
XENIA_CANARY_LICENSE_FILE = LICENSE

XENIA_CANARY_DEPENDENCIES = python-toml

# ugly hack becuase the is no version in the source file
define XENIA_CANARY_CLEAR_DL
    if [ -f "$(DL_DIR)/$(XENIA_CANARY_DL_SUBDIR)/$(XENIA_CANARY_SOURCE)" ]; then \
        rm $(DL_DIR)/$(XENIA_CANARY_DL_SUBDIR)/$(XENIA_CANARY_SOURCE); \
    fi
endef

define XENIA_CANARY_EXTRACT_CMDS
	mkdir -p $(@D) && cd $(@D) && $(UNZIP) -d $(@D) $(DL_DIR)/$(XENIA_CANARY_DL_SUBDIR)/$(XENIA_CANARY_SOURCE)
endef

define XENIA_CANARY_INSTALL_TARGET_CMDS
	mkdir -p $(TARGET_DIR)/usr
	rsync -av --exclude=".*" $(@D)/ $(TARGET_DIR)/usr/xenia-canary/
endef

define XENIA_CANARY_POST_PROCESS
	# get the latest patches
	mkdir -p $(TARGET_DIR)/usr/xenia-canary/patches
	mkdir -p $(@D)/temp
	( cd $(@D)/temp && $(GIT) init && \
	  $(GIT) remote add origin https://github.com/xenia-canary/game-patches.git && \
	  $(GIT) config core.sparsecheckout true && \
	  echo "patches/*.toml" >> .git/info/sparse-checkout && \
	  $(GIT) pull --depth=1 origin main && \
	  mv -f patches/*.toml $(TARGET_DIR)/usr/xenia-canary/patches \
	)

	# Clean up the temporary directory
	rm -rf $(@D)/temp
endef

XENIA_CANARY_PRE_DOWNLOAD_HOOKS = XENIA_CANARY_CLEAR_DL
XENIA_CANARY_POST_INSTALL_TARGET_HOOKS = XENIA_CANARY_POST_PROCESS

$(eval $(generic-package))
else
XENIA_CANARY_VERSION = fbd620c22b44638b66a70bba80d6f30d55a10924
XENIA_CANARY_SITE = https://github.com/xenia-canary/xenia-canary.git
XENIA_CANARY_SITE_METHOD = git
XENIA_CANARY_GIT_SUBMODULES = YES
XENIA_CANARY_LICENSE = BSD
XENIA_CANARY_LICENSE_FILE = LICENSE
XENIA_CANARY_SUPPORTS_IN_SOURCE_BUILD = NO

XENIA_CANARY_DEPENDENCIES = host-ninja host-pkgconf host-spirv-tools host-glslang \
    sdl2 vulkan-headers vulkan-loader lz4 alsa-lib libgtk3 xlib_libX11 libxcb \
    python-toml

ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_SM8X50),y)
XENIA_CANARY_OPT_FLAGS += \
	-O3 \
	-fno-semantic-interposition \
	-fomit-frame-pointer \
	-mcpu=cortex-x3
XENIA_CANARY_LINK_FLAGS += -Wl,-O2 -Wl,--as-needed
endif

XENIA_CANARY_CONF_OPTS += -DCMAKE_BUILD_TYPE=Release
XENIA_CANARY_CONF_OPTS += -DXENIA_BUILD_TESTS=OFF
XENIA_CANARY_CONF_OPTS += -DXENIA_BUILD_MISC=OFF
XENIA_CANARY_CONF_OPTS += -DXENIA_ENABLE_LTO=OFF
XENIA_CANARY_CONF_OPTS += -DCMAKE_C_FLAGS="$(TARGET_CFLAGS) $(XENIA_CANARY_OPT_FLAGS)"
XENIA_CANARY_CONF_OPTS += -DCMAKE_CXX_FLAGS="$(TARGET_CXXFLAGS) $(XENIA_CANARY_OPT_FLAGS)"
XENIA_CANARY_CONF_OPTS += -DCMAKE_EXE_LINKER_FLAGS="$(TARGET_LDFLAGS) $(XENIA_CANARY_LINK_FLAGS)"
XENIA_CANARY_CONF_ENV += VULKAN_SDK=
XENIA_CANARY_MAKE_ENV += VULKAN_SDK=

define XENIA_CANARY_APPLY_NATIVE_PATCHES
	$(APPLY_PATCHES) $(@D) $(XENIA_CANARY_PKGDIR)/native-patches \*.patch
endef

define XENIA_CANARY_GEN_VERSION_H
	mkdir -p $(@D)
	printf '// Autogenerated by batocera buildroot.\n\
#ifndef GENERATED_VERSION_H_\n\
#define GENERATED_VERSION_H_\n\
#define XE_BUILD_BRANCH "canary_experimental"\n\
#define XE_BUILD_COMMIT "$(XENIA_CANARY_VERSION)"\n\
#define XE_BUILD_COMMIT_SHORT "$(shell echo $(XENIA_CANARY_VERSION) | cut -c1-7)"\n\
#define XE_BUILD_DATE __DATE__\n\
#define XE_BUILD_PR_NUMBER 0\n\
#endif  // GENERATED_VERSION_H_\n' > $(@D)/version.h
endef

define XENIA_CANARY_INSTALL_TARGET_CMDS
	find $(@D) -maxdepth 6 -name "xenia_canary" -type f -perm /111 \
	    | head -1 \
	    | xargs -I{} $(INSTALL) -D -m 0755 {} $(TARGET_DIR)/usr/xenia-canary/xenia_canary
	mkdir -p $(TARGET_DIR)/usr/bin
	ln -sf ../xenia-canary/xenia_canary $(TARGET_DIR)/usr/bin/xenia-canary

	mkdir -p $(TARGET_DIR)/usr/share/xenia-canary/patches
	mkdir -p $(@D)/temp-patches
	( cd $(@D)/temp-patches && $(GIT) init && \
	  $(GIT) remote add origin https://github.com/xenia-canary/game-patches.git && \
	  $(GIT) config core.sparsecheckout true && \
	  echo "patches/*.toml" >> .git/info/sparse-checkout && \
	  $(GIT) pull --depth=1 origin main && \
	  mv -f patches/*.toml \
	      $(TARGET_DIR)/usr/share/xenia-canary/patches \
	)
	rm -rf $(@D)/temp-patches
endef

XENIA_CANARY_POST_PATCH_HOOKS += XENIA_CANARY_APPLY_NATIVE_PATCHES
XENIA_CANARY_PRE_CONFIGURE_HOOKS += XENIA_CANARY_GEN_VERSION_H

$(eval $(cmake-package))
endif
