################################################################################
#
# rapidyaml
#
################################################################################

RAPIDYAML_VERSION = v0.10.0
RAPIDYAML_SITE = https://github.com/biojppm/rapidyaml
RAPIDYAML_SITE_METHOD = git
RAPIDYAML_GIT_SUBMODULES = YES
RAPIDYAML_LICENSE = MIT
RAPIDYAML_LICENSE_FILES = LICENSE.txt
RAPIDYAML_SUPPORTS_IN_SOURCE_BUILD = NO
RAPIDYAML_INSTALL_STAGING = YES
RAPIDYAML_INSTALL_TARGET = NO

RAPIDYAML_CONF_OPTS += -DCMAKE_BUILD_TYPE=Release
RAPIDYAML_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
RAPIDYAML_CONF_OPTS += -DCMAKE_POSITION_INDEPENDENT_CODE=ON
RAPIDYAML_CONF_OPTS += -DRYML_BUILD_TESTS=OFF
RAPIDYAML_CONF_OPTS += -DRYML_BUILD_TOOLS=OFF
RAPIDYAML_CONF_OPTS += -DRYML_BUILD_BENCHMARKS=OFF

$(eval $(cmake-package))
